import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.179.1/build/three.module.js';
import { GLTFLoader } from 'https://cdn.jsdelivr.net/npm/three@0.179.1/examples/jsm/loaders/GLTFLoader.js';
import { clone as cloneSkinned } from 'https://cdn.jsdelivr.net/npm/three@0.179.1/examples/jsm/utils/SkeletonUtils.js';

const $=id=>document.getElementById(id), canvas=$('game');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));
renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene(); scene.background=new THREE.Color(0xa9cfda); scene.fog=new THREE.FogExp2(0xa9cfda,.006);
const camera=new THREE.PerspectiveCamera(42,1,.1,600); const MAP=300, HALF=150;
scene.add(new THREE.HemisphereLight(0xf2fbff,0x38513d,2.1));
const sun=new THREE.DirectionalLight(0xffefd0,2.8); sun.position.set(55,85,40); sun.castShadow=true; sun.shadow.mapSize.set(2048,2048); scene.add(sun);
const mat=(c,o={})=>new THREE.MeshStandardMaterial({color:c,roughness:o.r??.8,metalness:o.m??0,emissive:o.e??0,emissiveIntensity:o.i??0});
const ground=new THREE.Mesh(new THREE.PlaneGeometry(MAP,MAP),mat(0x52964a)); ground.rotation.x=-Math.PI/2; ground.receiveShadow=true; scene.add(ground);
const pathMat=mat(0xc8b27b); function road(w,h,x,z){const p=new THREE.Mesh(new THREE.PlaneGeometry(w,h),pathMat);p.rotation.x=-Math.PI/2;p.position.set(x,.02,z);p.receiveShadow=true;scene.add(p)} road(18,MAP,0,0); road(MAP,16,0,0);
const obstacles=[]; function tree(x,z,s=1){const g=new THREE.Group();const t=new THREE.Mesh(new THREE.CylinderGeometry(.65*s,.9*s,5*s,8),mat(0x6c452a));t.position.y=2.5*s;g.add(t);for(let i=0;i<2;i++){const c=new THREE.Mesh(new THREE.ConeGeometry((3.5-i*.7)*s,(5.3-i*.5)*s,9),mat(i?0x337844:0x285f39));c.position.y=(6.3+i*2.5)*s;g.add(c)}g.position.set(x,0,z);g.traverse(n=>{if(n.isMesh){n.castShadow=n.receiveShadow=true}});scene.add(g);obstacles.push({x,z,r:2*s})}
function rock(x,z,s=1){const r=new THREE.Mesh(new THREE.DodecahedronGeometry(1.4*s,0),mat(0x78827b));r.scale.set(1.25,.7,1);r.position.set(x,.8*s,z);r.castShadow=r.receiveShadow=true;scene.add(r);obstacles.push({x,z,r:1.6*s})}
let seed=20260813;function rng(){seed|=0;seed=seed+0x6D2B79F5|0;let t=seed;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}
for(let i=0;i<56;i++){let x=(rng()-.5)*275,z=(rng()-.5)*275;if(Math.abs(x)<24||Math.abs(z)<21){i--;continue}tree(x,z,.7+rng()*.5)}for(let i=0;i<24;i++){let x=(rng()-.5)*270,z=(rng()-.5)*270;if(Math.abs(x)<23||Math.abs(z)<20){i--;continue}rock(x,z,.65+rng()*.5)}

const MODEL_BASE='https://raw.githubusercontent.com/Anaszan/Python-Dungeon-Rise-of-the-Conqueror/e1dfcf47235b5a9a39f53b9428ba42ffed2f6eeb/public/models/female/';
const defs={
  man:{url:MODEL_BASE+'Adventurer.glb',primary:'#1f70c9',secondary:'#f1f1ec',accent:'#54b9ff'},
  woman:{url:MODEL_BASE+'Witch.glb',primary:'#7134aa',secondary:'#f2eef1',accent:'#b14cff'},
  alt:{url:MODEL_BASE+'HoodedAdventurer.glb',primary:'#007f78',secondary:'#17282b',accent:'#39efb4'}
};
const loader=new GLTFLoader(), cache={}; let chosen='man', modelRoot=null, mixer=null, actions={}, currentAction=null;
const player=new THREE.Group(); scene.add(player);

function recolor(root,type){const d=defs[type];root.traverse(o=>{if(!o.isMesh)return;o.castShadow=true;o.receiveShadow=true;const src=Array.isArray(o.material)?o.material:[o.material];const arr=src.map(m=>{const n=m.clone();const name=(m.name||'').toLowerCase();if(name.includes('skin')){}else if(name.includes('hair')){if(type==='woman')n.color.set('#5e298d');else if(type==='man')n.color.set('#17263d');else n.color.set('#111718')}else if(name.includes('purple')||name.includes('green')||name.includes('brown')||name.includes('cloth')||name.includes('dress')||name.includes('shirt')||name.includes('robe')) n.color.set(d.primary);else if(name.includes('gold')||name.includes('metal')) n.color.set('#c9a24b');n.roughness=Math.max(.45,n.roughness??.8);return n});o.material=Array.isArray(o.material)?arr:arr[0]});}
function fitModel(root,type){root.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(root),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());const target=type==='man'?8.8:8.4,scale=target/Math.max(.001,size.y);root.scale.setScalar(scale);root.updateMatrixWorld(true);const box2=new THREE.Box3().setFromObject(root);const min=box2.min;root.position.y-=min.y;root.position.x-=center.x*scale;root.position.z-=center.z*scale;if(type==='man'){root.scale.x*=1.12;root.scale.z*=1.08}}
function pickClip(clips,rx){return clips.find(c=>rx.test(c.name))||null}
function playAnim(name){const a=actions[name];if(!a||currentAction===a)return;if(currentAction)currentAction.fadeOut(.18);a.reset().fadeIn(.18).play();currentAction=a}
async function loadCharacter(type){chosen=type;if(modelRoot){player.remove(modelRoot);modelRoot=null}mixer=null;actions={};currentAction=null;$('hint').textContent='Cargando personaje 3D…';try{let gltf=cache[type];if(!gltf){gltf=await new Promise((res,rej)=>loader.load(defs[type].url,res,undefined,rej));cache[type]=gltf}const root=cloneSkinned(gltf.scene);recolor(root,type);fitModel(root,type);modelRoot=root;player.add(root);mixer=new THREE.AnimationMixer(root);const idle=pickClip(gltf.animations,/idle/i)||gltf.animations[0],walk=pickClip(gltf.animations,/walk|run/i),attack=pickClip(gltf.animations,/attack|punch|slash/i);if(idle)actions.idle=mixer.clipAction(idle);if(walk)actions.walk=mixer.clipAction(walk);if(attack){actions.attack=mixer.clipAction(attack);actions.attack.setLoop(THREE.LoopOnce,1);actions.attack.clampWhenFinished=true}playAnim('idle');$('hint').textContent='WASD / flechas · ESPACIO atacar · E abrir cofre'}catch(e){console.error(e);$('hint').textContent='No se pudo cargar el modelo 3D';}}

const enemyMat=[0x76459c,0x62ad5b,0xb34d4d,0x44484f];const enemies=[];for(let i=0;i<36;i++){const g=new THREE.Group();const b=new THREE.Mesh(new THREE.IcosahedronGeometry(1.7,1),mat(enemyMat[i%enemyMat.length]));b.position.y=1.8;g.add(b);const eye=new THREE.Mesh(new THREE.SphereGeometry(.35,8,6),mat(0xffefb0,{e:0xffcc55,i:1}));eye.position.set(0,2.1,1.45);g.add(eye);let x,z;do{x=(rng()-.5)*265;z=(rng()-.5)*265}while(Math.hypot(x,z)<28);g.position.set(x,0,z);g.traverse(n=>{if(n.isMesh)n.castShadow=true});scene.add(g);enemies.push({mesh:g,hp:100,speed:3.5+rng()*1.2,strength:8,alive:true})}
const chests=[];for(const [x,z] of[[-35,-38],[40,-42],[-68,22],[72,26],[-32,78],[36,85],[-95,-55],[96,-50],[0,-108],[0,112]]){const g=new THREE.Group();const b=new THREE.Mesh(new THREE.BoxGeometry(4.6,2.3,3.4),mat(0x704424));b.position.y=1.2;g.add(b);const lid=new THREE.Mesh(new THREE.BoxGeometry(4.8,1.2,3.6),mat(0xc79b32,{m:.35}));lid.position.y=3.05;g.add(lid);const l=new THREE.PointLight(0xffd46a,1.4,12);l.position.y=4;g.add(l);g.position.set(x,0,z);g.traverse(n=>{if(n.isMesh)n.castShadow=true});scene.add(g);chests.push({mesh:g,lid,light:l,opened:false})}

let started=false,paused=true,gameOver=false,health=1000,knowledge=0,correct=0,answered=0,kills=0,opened=0,attackCD=0,damageCD=0,activeChest=null,currentQ=null;
const keys={};addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='Space'){e.preventDefault();attack()}if(e.code==='KeyE')tryChest()});addEventListener('keyup',e=>keys[e.code]=false);
let joy={x:0,y:0};const joyEl=$('joy'),knob=$('knob');function setJoy(x,y){const r=joyEl.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;let dx=x-cx,dy=y-cy,max=r.width*.32,l=Math.hypot(dx,dy)||1;if(l>max){dx=dx/l*max;dy=dy/l*max}joy.x=dx/max;joy.y=dy/max;knob.style.transform=`translate(${dx}px,${dy}px)`}function resetJoy(){joy.x=joy.y=0;knob.style.transform='translate(0,0)'}joyEl.addEventListener('pointerdown',e=>{joyEl.setPointerCapture(e.pointerId);setJoy(e.clientX,e.clientY)});joyEl.addEventListener('pointermove',e=>{if(joyEl.hasPointerCapture(e.pointerId))setJoy(e.clientX,e.clientY)});joyEl.addEventListener('pointerup',resetJoy);joyEl.addEventListener('pointercancel',resetJoy);

const AUDIO='https://cdn.jsdelivr.net/gh/aguilanh4-ui/juego-quimica@main/assets/sound/',intro=new Audio(AUDIO+'intro.mp3'),overworld=new Audio(AUDIO+'overworld.ogg'),gameoverAudio=new Audio(AUDIO+'game-over.mp3');intro.loop=true;overworld.loop=true;intro.volume=.35;overworld.volume=.28;const play=a=>a.play().catch(()=>{});
document.querySelectorAll('.char').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.char').forEach(x=>x.classList.remove('sel'));b.classList.add('sel');loadCharacter(b.dataset.char);play(intro)}));
$('start').addEventListener('click',async()=>{if(!modelRoot)await loadCharacter(chosen);intro.pause();play(overworld);$('menu').style.display='none';started=true;paused=false});

function collides(x,z){if(x<-HALF+3||x>HALF-3||z<-HALF+3||z>HALF-3)return true;return obstacles.some(o=>Math.hypot(x-o.x,z-o.z)<o.r+1.3)}
function attack(){if(!started||paused||gameOver||attackCD>0)return;attackCD=.6;if(actions.attack){playAnim('attack');setTimeout(()=>playAnim('idle'),450)}for(const e of enemies){if(!e.alive)continue;if(player.position.distanceTo(e.mesh.position)<7.2){e.hp-=60;if(e.hp<=0){e.alive=false;scene.remove(e.mesh);kills++;knowledge+=20;hud()}}}}
function nearestChest(){let best=null,d=999;for(const c of chests){if(c.opened)continue;const q=player.position.distanceTo(c.mesh.position);if(q<d){d=q;best=c}}return d<7.5?best:null}function tryChest(){if(!started||paused||gameOver)return;const c=nearestChest();if(c)openQuiz(c)}$('action').addEventListener('click',()=>nearestChest()?tryChest():attack());
function openQuiz(c){const bank=Array.isArray(window.BIOCHEM_QUESTIONS)?window.BIOCHEM_QUESTIONS:[];if(!bank.length)return;activeChest=c;paused=true;currentQ=bank[Math.floor(Math.random()*bank.length)];$('qcat').textContent=currentQ.category;$('qtext').textContent=currentQ.question;$('feedback').style.display='none';$('continueQuiz').style.display='none';const a=$('answers');a.innerHTML='';currentQ.options.forEach((op,i)=>{const b=document.createElement('button');b.className='answer';b.textContent=String.fromCharCode(65+i)+') '+op;b.onclick=()=>answer(i,b);a.appendChild(b)});$('quiz').style.display='grid'}
function answer(i,b){if(b.dataset.done)return;[...$('answers').children].forEach(x=>x.dataset.done='1');answered++;const ok=i===currentQ.answer;if(ok){correct++;knowledge+=100;health=Math.min(1000,health+25);b.classList.add('correct')}else{health=Math.max(0,health-50);b.classList.add('wrong');$('answers').children[currentQ.answer]?.classList.add('correct')}$('feedback').style.display='block';$('feedback').innerHTML=`<strong>${ok?'¡Correcto! +100 conocimiento':'Respuesta incorrecta · -50 vida'}</strong><br>${currentQ.explanation}`;$('continueQuiz').style.display='inline-block';if(activeChest&&!activeChest.opened){activeChest.opened=true;opened++;activeChest.lid.rotation.x=-.75;activeChest.light.intensity=.2}hud();if(health<=0)setTimeout(over,400)}$('continueQuiz').onclick=()=>{$('quiz').style.display='none';if(health>0)paused=false};
function hud(){$('lifeText').textContent=`${Math.ceil(health)} / 1000`;$('lifeFill').style.width=`${Math.max(0,health/10)}%`;$('knowledgeText').textContent=`${knowledge} pts`;$('knowledgeFill').style.width=`${Math.min(100,knowledge/10)}%`;$('questionsText').textContent=`${correct}/${answered}`;$('killsText').textContent=kills;$('chestsText').textContent=opened}function over(){if(gameOver)return;gameOver=true;paused=true;overworld.pause();play(gameoverAudio);$('goKnowledge').textContent=knowledge;$('goCorrect').textContent=`${correct}/${answered}`;$('goKills').textContent=kills;$('quiz').style.display='none';$('gameover').style.display='grid'}$('retry').onclick=$('changeChar').onclick=()=>location.reload();

const clock=new THREE.Clock();function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.fov=innerWidth<innerHeight?54:42;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();loadCharacter('man');
function loop(){const dt=Math.min(clock.getDelta(),.033);attackCD=Math.max(0,attackCD-dt);damageCD=Math.max(0,damageCD-dt);if(mixer)mixer.update(dt);let moving=false;if(started&&!paused&&!gameOver){let x=0,z=0;if(keys.KeyA||keys.ArrowLeft)x--;if(keys.KeyD||keys.ArrowRight)x++;if(keys.KeyW||keys.ArrowUp)z--;if(keys.KeyS||keys.ArrowDown)z++;x+=joy.x;z+=joy.y;const l=Math.hypot(x,z);if(l>.08){moving=true;x/=Math.max(1,l);z/=Math.max(1,l);const sp=18,nx=player.position.x+x*sp*dt,nz=player.position.z+z*sp*dt;if(!collides(nx,player.position.z))player.position.x=nx;if(!collides(player.position.x,nz))player.position.z=nz;player.rotation.y=Math.atan2(x,z);if(actions.walk)playAnim('walk')}else playAnim('idle');for(const e of enemies){if(!e.alive)continue;const dx=player.position.x-e.mesh.position.x,dz=player.position.z-e.mesh.position.z,d=Math.hypot(dx,dz);if(d<30&&d>3.5){e.mesh.position.x+=dx/d*e.speed*dt;e.mesh.position.z+=dz/d*e.speed*dt}if(d<4.2&&damageCD<=0){health-=e.strength;damageCD=.55;hud();if(health<=0)over()}}$('hint').textContent=nearestChest()?'Cofre cercano: pulsa E o ACCIÓN para abrir':'WASD / flechas · ESPACIO atacar · E abrir cofre'}const off=innerWidth<innerHeight?new THREE.Vector3(15,27,23):new THREE.Vector3(19,22,25),des=player.position.clone().add(off);camera.position.lerp(des,1-Math.pow(.0015,dt));const look=player.position.clone();look.y=3.6;look.z-=3;camera.lookAt(look);renderer.render(scene,camera);requestAnimationFrame(loop)}hud();loop();