import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.179.1/build/three.module.js';

const $=id=>document.getElementById(id);
const canvas=$('game');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true});
renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.65));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x91c7d8);scene.fog=new THREE.Fog(0x91c7d8,125,255);
const camera=new THREE.PerspectiveCamera(48,1,.1,650);
const MAP=300,HALF=150;
scene.add(new THREE.HemisphereLight(0xdff6ff,0x2b3b27,2.05));
const sun=new THREE.DirectionalLight(0xfff3cf,2.15);sun.position.set(55,85,30);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(MAP,MAP),new THREE.MeshStandardMaterial({color:0x4d963f,roughness:.98}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
const pathMat=new THREE.MeshStandardMaterial({color:0xb99865,roughness:1});function path(w,h,x,z){const m=new THREE.Mesh(new THREE.PlaneGeometry(w,h),pathMat);m.rotation.x=-Math.PI/2;m.position.set(x,.012,z);m.receiveShadow=true;scene.add(m)}path(20,MAP,0,0);path(MAP,18,0,0);path(14,120,-72,-45);path(14,130,78,42);
const obstacles=[];function box(x,z,w,d,h,color){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,roughness:.82}));m.position.set(x,h/2,z);m.castShadow=true;m.receiveShadow=true;scene.add(m);obstacles.push({x,z,hw:w/2+1.2,hd:d/2+1.2});return m}function tree(x,z,s=1){const tr=new THREE.Mesh(new THREE.CylinderGeometry(1*s,1.25*s,5*s,8),new THREE.MeshStandardMaterial({color:0x74512f}));tr.position.set(x,2.5*s,z);tr.castShadow=true;scene.add(tr);const cr=new THREE.Mesh(new THREE.IcosahedronGeometry(3.8*s,1),new THREE.MeshStandardMaterial({color:0x2b713b,roughness:1}));cr.position.set(x,7*s,z);cr.castShadow=true;scene.add(cr);obstacles.push({x,z,hw:2.1*s,hd:2.1*s})}
box(-105,-95,34,24,13,0xdce4e8);box(105,-92,38,26,16,0xcbd8df);box(-108,96,30,28,14,0xe2ded0);box(108,100,42,25,15,0xbcd5ca);for(const [x,z] of [[-105,-75],[105,-70],[-108,75],[108,78]])box(x,z,13,5,4,0x3e7184);
function mulberry32(a){return function(){let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}const rng=mulberry32(20260813);for(let i=0;i<82;i++){let x=(rng()-.5)*(MAP-24),z=(rng()-.5)*(MAP-24);if(Math.abs(x)<20||Math.abs(z)<18||(Math.abs(x)>88&&Math.abs(z)>70)){i--;continue}tree(x,z,.72+rng()*.55)}for(let i=0;i<22;i++){let x=(rng()-.5)*(MAP-30),z=(rng()-.5)*(MAP-30);if(Math.abs(x)<18||Math.abs(z)<18){i--;continue}box(x,z,2+rng()*3,2+rng()*3,1.5+rng()*2,0x71806b)}

let chosen='man',started=false,paused=true,gameOver=false;const palette={man:0x3e8fe0,woman:0xa55fd1,alt:0x42a96b};
const player=new THREE.Group(),bodyMat=new THREE.MeshStandardMaterial({color:palette.man,roughness:.58});const body=new THREE.Mesh(new THREE.CapsuleGeometry(1.7,3.7,5,10),bodyMat);body.position.y=3.4;body.castShadow=true;player.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(1.45,18,14),new THREE.MeshStandardMaterial({color:0xe5b88e}));head.position.y=7.2;head.castShadow=true;player.add(head);const hat=new THREE.Mesh(new THREE.ConeGeometry(2.1,3.3,12),new THREE.MeshStandardMaterial({color:0x23313a}));hat.position.y=9.2;hat.castShadow=true;player.add(hat);scene.add(player);
let health=1000,knowledge=0,correct=0,answered=0,kills=0,opened=0,attackCooldown=0,damageCooldown=0;

const enemies=[];const enemyColors=[0xdce1e8,0x8dcc6d,0x734b99,0x8b8c94,0xc45353];function makeEnemy(i){const g=new THREE.Group();const mat=new THREE.MeshStandardMaterial({color:enemyColors[i%enemyColors.length],roughness:.7});const b=new THREE.Mesh(new THREE.CapsuleGeometry(1.35,2.5,4,8),mat);b.position.y=2.7;b.castShadow=true;g.add(b);const h=new THREE.Mesh(new THREE.SphereGeometry(1.15,12,10),new THREE.MeshStandardMaterial({color:i%5===0?0xe9e3d6:enemyColors[i%enemyColors.length]}));h.position.y=5.5;h.castShadow=true;g.add(h);let x,z;do{x=(rng()-.5)*(MAP-35);z=(rng()-.5)*(MAP-35)}while(Math.hypot(x,z)<30||collides(x,z));g.position.set(x,0,z);scene.add(g);enemies.push({mesh:g,hp:80+(i%5)*25,speed:3.8+(i%4)*.65,strength:7+(i%4)*2,alive:true})}for(let i=0;i<50;i++)makeEnemy(i);

const chests=[];function makeChest(x,z){const g=new THREE.Group();const base=new THREE.Mesh(new THREE.BoxGeometry(4.5,2.5,3.4),new THREE.MeshStandardMaterial({color:0x6d3f20,roughness:.72}));base.position.y=1.3;base.castShadow=true;g.add(base);const lid=new THREE.Mesh(new THREE.BoxGeometry(4.7,1.25,3.6),new THREE.MeshStandardMaterial({color:0xc99632,metalness:.25,roughness:.5}));lid.position.y=3.15;lid.castShadow=true;g.add(lid);const glow=new THREE.PointLight(0xffd766,1.3,13);glow.position.y=4.5;g.add(glow);g.position.set(x,0,z);scene.add(g);chests.push({mesh:g,opened:false})}for(const p of [[-34,-35],[38,-41],[-67,18],[70,24],[-30,76],[34,83],[-92,-55],[93,-49],[-91,55],[91,61],[0,-105],[0,110]])makeChest(...p);

const keys={};addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='Space'){e.preventDefault();attack()}if(e.code==='KeyE')tryChest()});addEventListener('keyup',e=>keys[e.code]=false);
let joy={x:0,y:0};const joyEl=$('joy'),knob=$('knob');function setJoy(x,y){const r=joyEl.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;let dx=x-cx,dy=y-cy,max=r.width*.32,l=Math.hypot(dx,dy)||1;if(l>max){dx=dx/l*max;dy=dy/l*max}joy.x=dx/max;joy.y=dy/max;knob.style.transform=`translate(${dx}px,${dy}px)`}function resetJoy(){joy.x=joy.y=0;knob.style.transform='translate(0,0)'}joyEl.addEventListener('pointerdown',e=>{joyEl.setPointerCapture(e.pointerId);setJoy(e.clientX,e.clientY)});joyEl.addEventListener('pointermove',e=>{if(joyEl.hasPointerCapture(e.pointerId))setJoy(e.clientX,e.clientY)});joyEl.addEventListener('pointerup',resetJoy);joyEl.addEventListener('pointercancel',resetJoy);$('action').addEventListener('click',()=>{if(nearestChest())tryChest();else attack();});

const AUDIO='https://cdn.jsdelivr.net/gh/aguilanh4-ui/juego-quimica@main/assets/sound/';const intro=new Audio(AUDIO+'intro.mp3'),overworld=new Audio(AUDIO+'overworld.ogg'),gameoverAudio=new Audio(AUDIO+'game-over.mp3'),clickAudio=new Audio(AUDIO+'selection-click.wav');intro.loop=true;intro.volume=.38;overworld.loop=true;overworld.volume=.3;gameoverAudio.volume=.55;clickAudio.volume=.32;
function safePlay(a){a.play().catch(()=>{})}document.querySelectorAll('.char').forEach(btn=>{btn.addEventListener('pointerenter',()=>{clickAudio.currentTime=0;safePlay(clickAudio)});btn.addEventListener('click',()=>{document.querySelectorAll('.char').forEach(x=>x.classList.remove('sel'));btn.classList.add('sel');chosen=btn.dataset.char;bodyMat.color.setHex(palette[chosen]);safePlay(intro)})});
$('start').addEventListener('click',()=>{intro.pause();overworld.currentTime=0;safePlay(overworld);$('menu').style.display='none';started=true;paused=false});

function collides(nx,nz){if(nx<-HALF+3||nx>HALF-3||nz<-HALF+3||nz>HALF-3)return true;for(const o of obstacles)if(Math.abs(nx-o.x)<o.hw+1.2&&Math.abs(nz-o.z)<o.hd+1.2)return true;return false}
function attack(){if(!started||paused||gameOver||attackCooldown>0)return;attackCooldown=.45;body.scale.set(1.18,.9,1.18);setTimeout(()=>body.scale.set(1,1,1),120);for(const e of enemies){if(!e.alive)continue;const d=player.position.distanceTo(e.mesh.position);if(d<8){e.hp-=55;e.mesh.scale.set(1.15,.8,1.15);setTimeout(()=>e.mesh.scale.set(1,1,1),100);if(e.hp<=0){e.alive=false;scene.remove(e.mesh);kills++;knowledge+=20;updateHUD()}}}}
function nearestChest(){let best=null,dist=999;for(const c of chests){if(c.opened)continue;const d=player.position.distanceTo(c.mesh.position);if(d<dist){dist=d;best=c}}return dist<8?best:null}function tryChest(){if(!started||paused||gameOver)return;const c=nearestChest();if(c)openQuiz(c)}

let activeChest=null,currentQ=null;const bank=()=>Array.isArray(window.BIOCHEM_QUESTIONS)?window.BIOCHEM_QUESTIONS:[];function openQuiz(chest){activeChest=chest;paused=true;const qs=bank();if(!qs.length){paused=false;return}currentQ=qs[Math.floor(Math.random()*qs.length)];$('qcat').textContent=currentQ.category;$('qtext').textContent=currentQ.question;$('feedback').style.display='none';$('continueQuiz').style.display='none';const a=$('answers');a.innerHTML='';currentQ.options.forEach((op,i)=>{const b=document.createElement('button');b.className='answer';b.textContent=String.fromCharCode(65+i)+') '+op;b.addEventListener('click',()=>answerQuestion(i,b));a.appendChild(b)});$('quiz').style.display='grid'}
function answerQuestion(i,button){if(button.dataset.done)return;[...$('answers').children].forEach(x=>x.dataset.done='1');answered++;const ok=i===currentQ.answer;if(ok){correct++;knowledge+=100;health=Math.min(1000,health+25);button.classList.add('correct')}else{health=Math.max(0,health-50);button.classList.add('wrong');$('answers').children[currentQ.answer]?.classList.add('correct')}$('feedback').style.display='block';$('feedback').innerHTML=`<strong>${ok?'¡Correcto! +100 conocimiento':'Respuesta incorrecta · -50 vida'}</strong><br>${currentQ.explanation}`;$('continueQuiz').style.display='inline-block';if(activeChest&&!activeChest.opened){activeChest.opened=true;opened++;activeChest.mesh.children[1].rotation.x=-.75;activeChest.mesh.children[1].position.z=-1;activeChest.mesh.children[2].intensity=.25}updateHUD();if(health<=0)setTimeout(showGameOver,500)}
$('continueQuiz').addEventListener('click',()=>{$('quiz').style.display='none';if(health>0)paused=false});

function updateHUD(){$('lifeText').textContent=`${Math.ceil(health)} / 1000`;$('lifeFill').style.width=`${Math.max(0,health/10)}%`;$('knowledgeText').textContent=`${knowledge} pts`;$('knowledgeFill').style.width=`${Math.min(100,knowledge/10)}%`;$('questionsText').textContent=`${correct}/${answered}`;$('killsText').textContent=kills;$('chestsText').textContent=opened}
function showGameOver(){if(gameOver)return;gameOver=true;paused=true;overworld.pause();gameoverAudio.currentTime=0;safePlay(gameoverAudio);$('goKnowledge').textContent=knowledge;$('goCorrect').textContent=`${correct}/${answered}`;$('goKills').textContent=kills;$('quiz').style.display='none';$('gameover').style.display='grid'}
function resetGame(){location.reload()}$('retry').addEventListener('click',resetGame);$('changeChar').addEventListener('click',resetGame);

const clock=new THREE.Clock();function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.fov=innerWidth<innerHeight?59:46;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();
function animate(){const dt=Math.min(clock.getDelta(),.033);attackCooldown=Math.max(0,attackCooldown-dt);damageCooldown=Math.max(0,damageCooldown-dt);if(started&&!paused&&!gameOver){let ix=0,iz=0;if(keys.KeyA||keys.ArrowLeft)ix--;if(keys.KeyD||keys.ArrowRight)ix++;if(keys.KeyW||keys.ArrowUp)iz--;if(keys.KeyS||keys.ArrowDown)iz++;ix+=joy.x;iz+=joy.y;const l=Math.hypot(ix,iz);if(l>.08){ix/=Math.max(1,l);iz/=Math.max(1,l);const sp=20,nx=player.position.x+ix*sp*dt,nz=player.position.z+iz*sp*dt;if(!collides(nx,player.position.z))player.position.x=nx;if(!collides(player.position.x,nz))player.position.z=nz;player.rotation.y=Math.atan2(ix,iz);body.position.y=3.4+Math.sin(performance.now()*.013)*.12}for(const e of enemies){if(!e.alive)continue;const dx=player.position.x-e.mesh.position.x,dz=player.position.z-e.mesh.position.z,d=Math.hypot(dx,dz);if(d<32&&d>3.5){e.mesh.position.x+=dx/d*e.speed*dt;e.mesh.position.z+=dz/d*e.speed*dt;e.mesh.rotation.y=Math.atan2(dx,dz)}if(d<4.6&&damageCooldown<=0){health-=e.strength;damageCooldown=.5;updateHUD();if(health<=0)showGameOver()}}const c=nearestChest();$('hint').textContent=c?'Cofre cercano: pulsa E o ACCIÓN para abrir':'WASD / flechas · ESPACIO atacar · E abrir cofre'}const portrait=innerWidth<innerHeight,desired=new THREE.Vector3(player.position.x,portrait?32:25,player.position.z+(portrait?25:30));camera.position.lerp(desired,1-Math.pow(.002,dt));camera.lookAt(player.position.x,2.6,player.position.z-4);renderer.render(scene,camera);requestAnimationFrame(animate)}updateHUD();animate();